version: '3.7'

services:

  app:
    image: node:18
    working_dir: /app
    network_mode: host
    command: sh -c "npm install -g pnpm && pnpm i && npm run dev"
    volumes:
      - ./app:/app
    labels:
      - "traefik.enable=false"